id: P006805
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:23:53.568997
source_metadata:
  id: bdr:W23674
  title: བློ་བཟང་བསྟན་པའི་དབང་ཕྱུག་གི་རྣམ་ཐར་དཔག་བསམ་ལྗོན་ཤིང
  author: ''
  volumes:
    95d0101af5a249a1954f4dd95a681d80:
      image_group_id: I1PD108004
      title: ''
      volume_number: 1
      total_pages: 86
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
