id: I5DDFCB3B
legacy_id: P006805
ocr_import_info:
  bdrc_scan_id: W23674
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T01:05:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:38:52.268234+00:00'
last_modified: 2022-09-02 09:39:03.851519
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23674
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23674
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་བཟང་བསྟན་པའི་དབང་ཕྱུག་གི་རྣམ་ཐར་དཔག་བསམ་ལྗོན་ཤིང་།
  author: བསོད་ནམས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.854463838503729
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1PD108004:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD108004
      total_pages: 86
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD108004.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.854463838503729
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
